---
tables:
    lenz_vat_id_validation_log:
        truncate: true
    bestit_amazon_access_token:
        truncate: true
    bestit_amazon_alexa_customer_sale_notification:
        truncate: true
    bestit_amazon_alexa_notifications:
        truncate: true
    bestit_amazon_alexa_oauth_access_token:
        truncate: true
    bestit_amazon_alexa_oauth_access_token_scope:
        truncate: true
    bestit_amazon_alexa_oauth_auth_code:
        truncate: true
    bestit_amazon_alexa_oauth_auth_code_scope:
        truncate: true
    bestit_amazon_alexa_oauth_client:
        truncate: true
    bestit_amazon_alexa_oauth_refresh_token:
        truncate: true
    bestit_amazon_alexa_oauth_scope:
        truncate: true
    bestit_amazon_alexa_sale_notification:
        truncate: true
    bestit_amazon_alexa_skill:
        truncate: true
    bestit_amazon_alexa_skill_manifest:
        truncate: true
    bestit_amazon_cache:
        truncate: true
    customer_migration:
        truncate: true
    import_kundengutscheine_tmp:
        truncate: true
    import_voucher_codes_redeemed:
        truncate: true
    migration_order:
        truncate: true
    migration_order_detail:
        truncate: true
    payenginecw_customer_context:
        truncate: true
    payenginecw_storage:
        truncate: true
    payenginecw_transaction:
        truncate: true
    s_core_payment_data:
        truncate: true
    s_core_payment_instance:
        truncate: true
    s_core_sessions:
        truncate: true
    s_core_sessions_backend:
        truncate: true
    s_customer_search_index:
        truncate: true
    s_customer_streams_mapping:
        truncate: true
    s_es_backlog:
        truncate: true
    s_order:
        converters:
            remote_address:
                converter: 'setValue'
                parameters:
                    value: '127.0.0.1'
    s_order_basket:
        truncate: true
    s_order_basket_attributes:
        truncate: true
    s_order_basket_saved:
        truncate: true
    s_order_basket_saved_items:
        truncate: true
    s_order_basket_signatures:
        truncate: true
    s_order_billingaddress:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            street:
                converter: 'faker'
                parameters:
                    formatter: 'streetAddress'
            zipcode:
                converter: 'faker'
                parameters:
                    formatter: 'postcode'
            city:
                converter: 'faker'
                parameters:
                    formatter: 'city'
            company:
                converter: 'faker'
                parameters:
                    formatter: 'company'
            department:
                converter: 'faker'
                parameters:
                    formatter: 'jobTitle'
            ustid:
                converter: 'setNull'
    s_order_comparisons:
        truncate: true
    s_order_details:
        truncate: true
    s_order_details_attributes:
        truncate: true
    s_order_documents:
        truncate: true
    s_order_documents_attributes:
        truncate: true
    s_order_esd:
        truncate: true
    s_order_history:
        truncate: true
    s_order_notes:
        truncate: true
    s_order_shippingaddress:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            street:
                converter: 'faker'
                parameters:
                    formatter: 'streetAddress'
            zipcode:
                converter: 'faker'
                parameters:
                    formatter: 'postcode'
            city:
                converter: 'faker'
                parameters:
                    formatter: 'city'
            company:
                converter: 'faker'
                parameters:
                    formatter: 'company'
            department:
                converter: 'faker'
                parameters:
                    formatter: 'jobTitle'
    s_plugin_reply_consentric_send_user_data_job:
        truncate: true
    s_statistics_article_impression:
        truncate: true
    s_statistics_currentusers:
        truncate: true
    s_statistics_pool:
        truncate: true
    s_statistics_referer:
        truncate: true
    s_statistics_search:
        truncate: true
    s_statistics_visitors:
        truncate: true
    s_user:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            password:
                converter: 'setValue'
                parameters:
                    value: 'randomized'
            email:
                converter: 'randomizeEmail'
                unique: true
            birthday:
                converter: 'randomDate'
    s_user_addresses:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            street:
                converter: 'faker'
                parameters:
                    formatter: 'streetAddress'
            zipcode:
                converter: 'faker'
                parameters:
                    formatter: 'postcode'
            city:
                converter: 'faker'
                parameters:
                    formatter: 'city'
            company:
                converter: 'faker'
                parameters:
                    formatter: 'company'
            department:
                converter: 'faker'
                parameters:
                    formatter: 'jobTitle'
    s_user_billingaddress:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            street:
                converter: 'faker'
                parameters:
                    formatter: 'streetAddress'
            zipcode:
                converter: 'faker'
                parameters:
                    formatter: 'postcode'
            city:
                converter: 'faker'
                parameters:
                    formatter: 'city'
            company:
                converter: 'faker'
                parameters:
                    formatter: 'company'
            department:
                converter: 'faker'
                parameters:
                    formatter: 'jobTitle'
            ustid:
                converter: 'setNull'
    s_user_shippingaddress:
        converters:
            firstname:
                converter: 'faker'
                parameters:
                    formatter: 'firstName'
            lastname:
                converter: 'faker'
                parameters:
                    formatter: 'lastName'
            street:
                converter: 'faker'
                parameters:
                    formatter: 'streetAddress'
            zipcode:
                converter: 'faker'
                parameters:
                    formatter: 'postcode'
            city:
                converter: 'faker'
                parameters:
                    formatter: 'city'
            company:
                converter: 'faker'
                parameters:
                    formatter: 'company'
            department:
                converter: 'faker'
                parameters:
                    formatter: 'jobTitle'
    s_articles_also_bought_ro:
        truncate: true
    s_core_log:
        truncate: true